### ISSUE TITLE
Course don't download

### ISSUE THREAD

**Issue by andremxmx** [ReneR97/domestika-downloader#1]
Download 1/19 Downloaded
Download 2/19 Downloaded
Download 3/19 Downloaded
Download 4/19 Downloaded
Download 5/19 Downloaded
Download 6/19 Downloaded
Download 7/19 Downloaded
Download 8/19 Downloaded
Download 9/19 Downloaded
Download 10/19 Downloaded
Download 11/19 Downloaded
Download 12/19 Downloaded
Download 13/19 Downloaded
Download 14/19 Downloaded
Download 15/19 Downloaded
Download 16/19 Downloaded
Download 17/19 Downloaded
Download 18/19 Downloaded
Download 19/19 Downloaded
All Videos Downloaded

but the folder have no video

**Comment by ReneR97** [comment]
Can you send me the course link you are trying to download?
will have a look at it when i am off work

**Comment by ReneR97** [comment]
ok, i couldnt reproduce the problem but i made an update to the tool that ads a debug option. 
when you open the index.js script you will find a variable called "debug", set that to true and start the script like normal. 
at the end it will create a log.json file. If you send me that i might be able to find out what the problem is.

**Comment by andremxmx** [comment]
Well, im so sorry your code  works perfectly my pc was the problem, ffmpeg missing, i have it on c:/tools, just put inside the app and works grate  

":[{"stdout":"15:08:40.686 INFO : N_m3u8DL-RE (Beta version) 20230111\r\n15:08:40.699 ERROR: ffmpeg not found, please download at: https://ffmpeg.org/download.html\r\n","stderr":""},{"

thanks for the debug and the code i love it!

and sorry for spend your time sir,

**Comment by ReneR97** [comment]
Gread to hear that it works now ^^. 
And dont worry, coding is passion and i love working on stuff ^^
