### ISSUE TITLE
stuck at opening a terminal

### ISSUE THREAD

**Issue by sarsifloat** [ReneR97/domestika-downloader#11]
not sure how to "open a terminal and type npm i"..

i've followed the instructions, pasted from Cookie-editor, downloaded and installed ffmpeg, N_m3u8DL-RE, but i don't know how to move forward from here. ^^; tried to use the command prompt but i'm stuck. help please? thanks!

**Comment by ReneR97** [comment]
The easiest way is if you have the folder you downloaded from here open in windows, click on the top bar 
![image](https://github.com/ReneR97/domestika-downloader/assets/57572162/b366ad37-33b6-484d-810e-c9658b4b7f28)

and type "cmd" and hit enter. 
This will open a terminal in the directory you are currently in and you can just start executing the commands one by one

**Comment by sarsifloat** [comment]
> The easiest way is if you have the folder you downloaded from here open in windows, click on the top bar ![image](https://user-images.githubusercontent.com/57572162/261392478-b366ad37-33b6-484d-810e-c9658b4b7f28.png)
> 
> and type "cmd" and hit enter. This will open a terminal in the directory you are currently in and you can just start executing the commands one by one

cool! it worked!! xD thank you very much :) though follow up question because i got an error:
![image](https://github.com/ReneR97/domestika-downloader/assets/142490439/2032d49e-a66a-4f34-bd11-974764817053)

been looking through past issues for clues but i'm not sure if there's anything that applies to my error TT U TT (i have node version 18.7 installed. could i have pasted the cookies at the wrong places? ;3; i'm pretty confident i copied the correct info though)

**Comment by ReneR97** [comment]
Could you send me a screenshot of everything you filled out?

**Comment by DanielRivas75** [comment]
same error "TypeError: Cannot read properties of undefined (reading 'length')" @sarsifloat ...
![image](https://github.com/ReneR97/domestika-downloader/assets/6911171/7f39e7e6-92a9-4ffc-adf4-ec232aed770d)

here are part of my values:
![image](https://github.com/ReneR97/domestika-downloader/assets/6911171/906dc5b8-f046-46dd-a466-ca54ba6adecb)

I'm seeing many "%" characters, could this be related to decoding text?

**Comment by DanielRivas75** [comment]
Ok, I guess I figured it out... I was trying to download a normal course with my "Plus subscription" My bad... I just can watch some courses with the plus subscription

**Comment by sarsifloat** [comment]
> Could you send me a screenshot of everything you filled out?

![image](https://github.com/ReneR97/domestika-downloader/assets/142490439/49454f16-2e97-4d77-af5e-6505f694ee07)

here's the screenshot (i hope i got got it right)

ah i don't have a plus subscription tho. i just bought this one course only in my account. xD
