### ISSUE TITLE
TypeError: Cannot read properties of null (reading '1')

### ISSUE THREAD

**Issue by hyk937** [ReneR97/domestika-downloader#16]
access_token = regex_token.exec(access_token)[1];
                                                 ^

TypeError: Cannot read properties of null (reading '1')
    at scrapeSite (/home/hyk-zorin/Videos/Domestika/domestika-downloader-main/index.js:71:50)

now there is no credentials cookie.. The name of the cookie is "remember_user_token"

**Comment by gregg-thompson** [comment]
Same issue. Any joy?

**Comment by nak21** [comment]
I had the same issue but remember_user_token is another property. I switched to another extension,CookieManager-CookieEditor by Joue and it showed the credentials property.
