### ISSUE TITLE
Error on macbook pro M1

### ISSUE THREAD

**Issue by DivineRobot93** [ReneR97/domestika-downloader#18]
Hey,
It's me again, when I enter "npm i" in the terminal, I have these errors,
I'm on a 2020 macbook pro M1, Node, ffmpeg, N_m3u8DL-RE downloaded and installed
Tried the mac fix from fran montiel, but still the same on the terminal

if anyone have a solution...
Thanks a lot

<img width="965" alt="1" src="https://github.com/ReneR97/domestika-downloader/assets/144865792/82c7ff21-a6cb-4fa5-9cb2-c5da65e07d05">

**Comment by nak21** [comment]
I downloaded the code today and it definitely has the package.json file.

**Comment by DivineRobot93** [comment]
Hey, thanks for the answer, will dowload again I guess

**Comment by DivineRobot93** [comment]
I have the package.json too, maybe it is that specific course that won't download ..

**Comment by nak21** [comment]
Have you changed directories to where index.js is located?

**Comment by leifniem** [comment]
You're trying to run a windows executable on Mac. You will need to adjust the code to use the Mac version of N_m3u8DL-RE
