### ISSUE TITLE
Can't download bundled course

### ISSUE THREAD

**Issue by nak21** [ReneR97/domestika-downloader#19]
Close #19

**Comment by nak21** [comment]
C:\PG\domestika>npm run start

> domestika-downloader@1.0.0 start
> node index.js

C:\PG\domestika\index.js:76
    final_project_id = final_data.data.relationships.video.data.id;
                                       ^

TypeError: Cannot read properties of undefined (reading 'relationships')
    at scrapeSite (C:\PG\domestika\index.js:76:40)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

Node.js v20.9.0

**Comment by ReneR97** [comment]
Hello,
sorry for the late answer, but i just pushed an update that adds a check that should take care of your problem, so the tool doesnt crash when there is no final project

**Comment by TSboy89** [comment]
Hi there,
First of all, I really appreciate your work, it is awesome.

Unfortunately I've ran into the same reading 'relationship' error code, bundled course final video issue with the updated code.
I've tried to use it with this bundled course. Note the spaces.
https://www.domestika.org/  en/courses/4840-ableton-live-and-push-for-beginners/course

Should I modify the index.js according to the course's titles?
The last title in the last course is U5: Practice.
Ive tried to insert this text to 81, 82 line, but no difference.
Could you please look into it?
Thank you!

**Comment by Iulipartenie** [comment]
When I try to download a bundle I get this: 
C:\Domestika-Course-Video-Downloader-main>npm start

> domestika-downloader@1.0.0 start
> node index.js

C:\Domestika-Course-Video-Downloader-main\index.js:72
    let final_project_id = regex_final.exec($(units[units.length - 1]).attr('href'))[1];
                                                                                    ^

TypeError: Cannot read properties of null (reading '1')
    at scrapeSite (C:\Domestika-Course-Video-Downloader-main\index.js:72:85)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

Node.js v18.17.1
