### ISSUE TITLE
NOT an issue

### ISSUE THREAD

**Issue by andremxmx** [ReneR97/domestika-downloader#2]
Hi!! Me again.

Can i use your code to make an electron app, i will put your github in the footer of the app

![image](https://user-images.githubusercontent.com/10226983/221343005-9793f84d-e37f-4b98-b942-bae159e7a3c3.png)

**Comment by ReneR97** [comment]
Ofcourse, i have no problem with that 🙂

**Comment by andremxmx** [comment]
> Ofcourse, i have no problem with that 🙂

ty sir!!!

**Comment by Krunsher** [comment]
Can you make it available?
