### ISSUE TITLE
No "credentials" cookie

### ISSUE THREAD

**Issue by souto64** [ReneR97/domestika-downloader#20]
Domestika.org just show this two cookies:
_domestika_session
remember_user_token

Using "remember_user_token" on _credentials_ report this error:

access_token = regex_token.exec(access_token)[1];
TypeError: Cannot read properties of null (reading '1')
    at scrapeSite (C:\Users\Openbravo\Downloads\Crochet\domestika-downloader-main\index.js:71:50)

**Comment by souto64** [comment]
Sorry, solved: You can check this value on "developer tools" (logged in)

**Comment by joelstitch** [comment]
I also don't see credentials anywhere. What do you mean by check on "developer mode" and "logged in"?

**Comment by ReneR97** [comment]
There are different ways to get the credentials cookie. One way is like in the description of the repo to just use the Cookie-Editor browser extension. 
Or if you dont want to install that, you can open the developer tools, go to the tab "Application", then on the left open the Cookies tab and select https://domestika.com. Then you should see all your cookies on the right side, click on the "credentials" cookie and copy the value of it

**Comment by joelstitch** [comment]
If I remember right I used a similar add on but on Firefox and that gave me the right info.
