### ISSUE TITLE
Not an issue but a fix - Missing videos (not downloaded) within a Unit

### ISSUE THREAD

**Issue by fram1963** [ReneR97/domestika-downloader#23]
Downloading works but sometimes there are videos within a Unit not being downloaded.  I found the problem.  If you go in the course page on Domestika and pick a unit, you will see 1 or more videos for that unit.  For some reason, some video title have a blank space at the end of the name (use inspect to see the code).

To fix the download problem related to the trailing blank space, I modified the index.js code to remove the trailing blank:

vData.title becomes vData.title.trimEnd() for both the video and subtitle:

let log = await exec(`N_m3u8DL-RE -sv res="1080*":codec=hvc1:for=best "${vData.playbackURL}" --save-dir "domestika_courses/${title}/${unit.title}" --save-name "${a}_${vData.title.trimEnd()}"`);
let log2 = await exec(`N_m3u8DL-RE --auto-subtitle-fix --sub-format SRT --select-subtitle lang="${subtitle_lang}":for=all "${vData.playbackURL}" --save-dir "domestika_courses/${title}/${unit.title}" --save-name "${a}_${vData.title.trimEnd()}"`);

Works like a charm now.

Cheers

**Comment by ReneR97** [comment]
Hey, 
thanks for the Fix 
If you want, you can create a pull request and i will merge it. 
If you dont want to, just let me know and i will just put it in myself :)

**Comment by fram1963** [comment]
Hi.  You're welcome. You can go ahead with creating the pull request.
Cheers.

**Comment by ReneR97** [comment]
Added the fix.
Thanks again
