### ISSUE TITLE
Seems like something has changed.

### ISSUE THREAD

**Issue by nak21** [ReneR97/domestika-downloader#24]
Close #24

**Comment by ReneR97** [comment]
If you havent used it for a while, be sure to swap out all the cookies. Some of them can change  overtime so they dont work anymore

**Comment by nak21** [comment]
Thanks for the reply,Rene. I'm not sure what you mean by "be sure to swap out all the cookies". 
I am talking about downloading a new course. And I delete my browser's cookies all the time.

**Comment by nak21** [comment]
I just tried to do a new download and it is not working.
This time it goes to about 3/15 and then stops with no error message.
I tried both firefox and chrome browsers and get the same thing.
I looked at what was downloaded and it was only the *.srt files.
Do you think domestika might have changed something?

**Comment by ReneR97** [comment]
hmm, strange. 
I just tried it with my account and it seems to work just fine. 

Could you try enabling debuging? 

Just set the "const debug = false;" to "const debug = true;" in the script and run it again. 

when its done it should create a "log.json" file, just send me that file so i can have a closer look.

**Comment by nak21** [comment]
No log.json file, just the following:
<img width="1280" alt="cmd_EHEZdwq6Wn" src="https://github.com/ReneR97/domestika-downloader/assets/28970813/9b749331-6baf-41ec-943e-82f48a66e42a">

**Comment by ReneR97** [comment]
hmm, looks like there is no final projekt in that course, or it couldnt be found. 

i pushed a fixed that should fix that. Could you try it? just redownload the projekt and try again.

**Comment by nak21** [comment]
this time the script downloaded the 'structure' of the course and some, but not all, of the .srt files.
What it didn't download were the .mp4 files.
