### ISSUE TITLE
Downloads Nothing

### ISSUE THREAD

**Issue by passion3545** [ReneR97/domestika-downloader#27]
> domestika-downloader@1.0.0 start
> node index.js

Only these two lines are displayed after that the cursor blinks it doesn't download anything

Now I get this error after changing few things

node:internal/deps/undici/undici:12345
    Error.captureStackTrace(err, this);
          ^

TypeError: fetch failed
    at node:internal/deps/undici/undici:12345:11
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async fetchFromApi (C:\Users\domestika-downloader-main\domestika-downloader-main\index.js:151:22)
    at async scrapeSite (C:\Users\domestika-downloader-main\domestika-downloader-main\index.js:73:22) {
  cause: Error: read ECONNRESET
      at TLSWrap.onStreamRead (node:internal/stream_base_commons:217:20) {
    errno: -4077,
    code: 'ECONNRESET',
    syscall: 'read'
  }
}

Node.js v20.11.1

**Comment by passion3545** [comment]
Is the credentials syntax correct {%22accessToken%22:%22xxxxxxxxccx%22%2C%22refreshToken%22:%22xxxxxxxxxxxxxxxxxxxxxxxxxx%22%2C%22isEmpty%22:false}

**Comment by ReneR97** [comment]
yes, that should be good

**Comment by passion3545** [comment]
ffmpeg i installed in c drive with path and also copied the bin folder to the domestika-downloader folder but i get the same above error.

![Screenshot 2024-02-18 195710](https://github.com/ReneR97/domestika-downloader/assets/34564637/faca85b4-6e71-4b1f-8a4e-f56b95835c10)

**Comment by 4REMi** [comment]
Hello! I have exactly the same problem as @passion3545 

    const response = await fetch(apiURL, {
                     ^

ReferenceError: fetch is not defined
    at fetchFromApi (C:\Users\rocash\Desktop\domestika-downloader-main\index.js:151:22)
    at scrapeSite (C:\Users\rocash\Desktop\domestika-downloader-main\index.js:73:28)

**Comment by ReneR97** [comment]
> ffmpeg i installed in c drive with path and also copied the bin folder to the domestika-downloader folder but i get the same above error.
> 
> ![Screenshot 2024-02-18 195710](https://private-user-images.githubusercontent.com/34564637/305722698-faca85b4-6e71-4b1f-8a4e-f56b95835c10.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk3NDc3MjMsIm5iZiI6MTcwOTc0NzQyMywicGF0aCI6Ii8zNDU2NDYzNy8zMDU3MjI2OTgtZmFjYTg1YjQtNmU3MS00YjFmLThhNGUtZjU2Yjk1ODM1YzEwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA2VDE3NTAyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM3Yjg1YWE0YmI0YTkyMGM2NmNlNzk3NWRhNGU0YjVlZDM3Njk2MjAzOWRlZTBhZDZkMjhkMjg5OTI3YjVlMzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.feG2EcoCwD1NIn8zKNN-8g3q8g2PR4xnr8OuAlc2Pmo)


Hey,
i justed merge a pull request with a lot of improvements and fixes.
Could you try redownloading everything and trying again? see if that fixes your problem.
