### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Prohibitive** [ReneR97/domestika-downloader#29]
Hello
My Account:
![image](https://github.com/ReneR97/domestika-downloader/assets/22181509/4284e59c-a757-4051-a324-9bf99231ac39)
My Config
![image](https://github.com/ReneR97/domestika-downloader/assets/22181509/4a446ef8-4d89-430a-b2e3-31b7167b9887)

Result:
C:\Users\Prohi\Downloads\domestika-downloader-main>npm run start

> domestika-downloader@1.0.0 start
> node index.js

C:\Users\Prohi\Downloads\domestika-downloader-main\index.js:135
        for (let i = 0; i < data.videos.length; i++) {
                                        ^

TypeError: Cannot read properties of undefined (reading 'length')
    at getInitialProps (C:\Users\Prohi\Downloads\domestika-downloader-main\index.js:135:41)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async scrapeSite (C:\Users\Prohi\Downloads\domestika-downloader-main\index.js:54:25)

Node.js v20.11.1

**Comment by Prohibitive** [comment]
@ReneR97 Pls Help me?
Thx alot

**Comment by ReneR97** [comment]
Hey, 
i justed merge a pull request with a lot of improvements and fixes. 
Could you try redownloading everything and trying again? see if that fixes your problem.

**Comment by Prohibitive** [comment]
> Hey, i justed merge a pull request with a lot of improvements and fixes. Could you try redownloading everything and trying again? see if that fixes your problem.

Hello thx for reply but new error:

5 Units Detected
C:\Users\Prohi\Downloads\domestika-downloader-main\index.js:174
        for (let i = 0; i < data.videos.length; i++) {
                                        ^

TypeError: Cannot read properties of undefined (reading 'length')
    at getInitialProps (C:\Users\Prohi\Downloads\domestika-downloader-main\index.js:174:41)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async scrapeSite (C:\Users\Prohi\Downloads\domestika-downloader-main\index.js:98:25)

Node.js v20.11.1

**Comment by ReneR97** [comment]
Are you sure you used the latest version? if you havent, you have to redownload the code from the git repository and try again. 
If the error still persists, let me know
