### ISSUE TITLE
'npm' is not recognized as an internal or external command

### ISSUE THREAD

**Issue by archz2** [ReneR97/domestika-downloader#34]
I am getting this error. 

![image](https://github.com/ReneR97/domestika-downloader/assets/66735186/58757c74-539e-4c04-b695-491cc805caa6)

**Comment by ReneR97** [comment]
you need to install nodejs https://nodejs.org/en

**Comment by archz2** [comment]
Thanks a lot. Some progress. I am getting this error now. 

![image](https://github.com/ReneR97/domestika-downloader/assets/66735186/413932dd-f8b0-419a-b21a-9ce6dd99b9a0)


TypeError: Cannot read properties of null (reading '1')
    at Object.<anonymous> (D:\DOMDOWN\index.js:36:64)
    at Module._compile (node:internal/modules/cjs/loader:1369:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1427:10)
    at Module.load (node:internal/modules/cjs/loader:1206:32)
    at Module._load (node:internal/modules/cjs/loader:1022:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:135:12)
    at node:internal/main/run_main_module:28:49

**Comment by ReneR97** [comment]
did you follow all the steps in the description of this repo?

**Comment by archz2** [comment]
Ok I followed all the steps except for adding the credentials cookie. When I open the cookie-editor app, I don't see any credential cookie.  I only see a stripe mid cookie and a session cookie. I am logged into my domestika account. 

Here's a screen recording of what I see. 

https://github.com/ReneR97/domestika-downloader/assets/66735186/e45bd8d5-7568-46e2-bd84-e28f6c234358

**Comment by ReneR97** [comment]
Hi, can you try using another Browser? 
Or if that doesnt help, try this to get the cookies https://www.cookieyes.com/blog/how-to-check-cookies-on-your-website-manually/

**Comment by Iulipartenie** [comment]
Try "CookieManager - Cookie Editor"
