### ISSUE TITLE
"Credentials" is not available

### ISSUE THREAD

**Issue by Pastacodng** [ReneR97/domestika-downloader#36]
"Credentials" is not available in the cookie-editor:

![Снимок экрана 2024-04-04 232739](https://github.com/ReneR97/domestika-downloader/assets/166068454/9b4a675c-f69e-46aa-a0d8-ef881c882db9)

**Comment by archz2** [comment]
Same happening with me. 
https://github.com/ReneR97/domestika-downloader/issues/34#issuecomment-2033555004

**Comment by ReneR97** [comment]
Hi, can you try using another Browser? 
Or if that doesnt help, try this to get the cookies https://www.cookieyes.com/blog/how-to-check-cookies-on-your-website-manually/

**Comment by Pastacodng** [comment]
> Hi, can you try using another Browser? Or if that doesnt help, try this to get the cookies https://www.cookieyes.com/blog/how-to-check-cookies-on-your-website-manually/

I've tried yandex, chrome and opera.  It's the same everywhere. And cookieyes require a foreign credit card, which I don't have.

**Comment by ReneR97** [comment]
the link is just a tutorial on how to get the cookie info without an extension

**Comment by Iulipartenie** [comment]
Try "CookieManager - Cookie Editor".

**Comment by Pastacodng** [comment]
The problem is solved. I used the wrong cookie editor. There are many different, different authors. Thanks!
