### ISSUE TITLE
Audio Language

### ISSUE THREAD

**Issue by ashonagi** [ReneR97/domestika-downloader#38]
This is not an issue or a big deal at all as much as a curious question.
Some courses are available in dual audio, and English is one of them. Is there a line I code to add to pick this audio instead of the original?
Example: https://www.domestika.org/en/courses/3019-creativity-for-beginners-level-1
![image](https://github.com/ReneR97/domestika-downloader/assets/166965146/4c8a4634-a876-428e-b627-ae46fcfa6e12)

Thanks

**Comment by ReneR97** [comment]
Currently not, would have to look into that
