### ISSUE TITLE
Errors, Errors, Errors ...

### ISSUE THREAD

**Issue by Hermit6202** [ReneR97/domestika-downloader#42]
Getting a lot of errors:
`Video Found: Introduction and materials
Video Found: Ink 1
Video Found: Ink 2
Video Found: Watercolor 1
Video Found: Watercolor 2
Video Found: Ink and watercolor
Video Found: Hundertwasser
Video Found: The five skins
Video Found: Theme and documentation
Video Found: Character 1
Video Found: Character 2
Video Found: Home
Video Found: Community
Video Found: World
Video Found: Sketch and pose illustration
Video Found: Apply the color with watercolor
Video Found: Inking and final details
All Videos Found
Fetching Final Project
Download 1/20 Started
Download 2/20 Started
Download 3/20 Started
Download 4/20 Started
Download 5/20 Started
Download 6/20 Started
Download 7/20 Started
Download 8/20 Started
Download 9/20 Started
Download 10/20 Started
Download 11/20 Started
Download 12/20 Started
Download 13/20 Started
Download 14/20 Started
Download 15/20 Started
Download 16/20 Started
Download 17/20 Started
Download 18/20 Started
Download 19/20 Started
Download 20/20 Started
node:internal/errors:932
  const err = new Error(message);
              ^

Error: Command failed: N_m3u8DL-RE -sv res="1080*":codec=hvc1:for=best "https://cdn-videos.domestika.org/videos/000/042/099/e5fe1b566fe895531f3dadca95af8293/master.m3u8?1676400687" --save-dir "domestika_courses/Imaginary Worlds Illustrated with Ink and Watercolor//U5- Illustrated scene step by step" --save-name "2_Inking and final details"
Die Version von J:\@domestika-downloader\N_m3u8DL-RE.exe ist mit der ausgef�hrten Windows-Version nicht kompatibel. �berpr�fen Sie die Systeminformationen des Computers, und wenden Sie sich anschlie�end an den Herausgeber der Software.

    at ChildProcess.exithandler (node:child_process:422:12)
    at ChildProcess.emit (node:events:514:28)
    at maybeClose (node:internal/child_process:1105:16)
    at Socket.<anonymous> (node:internal/child_process:457:11)
    at Socket.emit (node:events:514:28)
    at Pipe.<anonymous> (node:net:337:12) {
  code: 1,
  killed: false,
  signal: null,
  cmd: 'N_m3u8DL-RE -sv res="1080*":codec=hvc1:for=best "https://cdn-videos.domestika.org/videos/000/042/099/e5fe1b566fe895531f3dadca95af8293/master.m3u8?1676400687" --save-dir "domestika_courses/Imaginary Worlds Illustrated with Ink and Watercolor//U5- Illustrated scene step by step" --save-name "2_Inking and final details"',
  stdout: '',
  stderr: 'Die Version von J:\\@domestika-downloader\\N_m3u8DL-RE.exe ist mit der ausgef�hrten Windows-Version nicht kompatibel. �berpr�fen Sie die Systeminformationen des Computers, und wenden Sie sich anschlie�end an den Herausgeber der Software.\r\n'
}

Node.js v20.10.0
PS J:\@domestika-downloader>`

**Comment by ReneR97** [comment]
whats your windows version?

**Comment by Hermit6202** [comment]
Than you for the quick reaction. It was my fault, I loaded the arm64
version instead the win64

Rene Reiterer ***@***.***> schrieb am Fr., 3. Mai 2024, 11:55:

**Comment by CoralineKoralina** [comment]
I have this issue even though I installed everything (this code, ffmpeg, N_m3u8DL-RE) for windows.

Error downloading video: Error: Command failed: N_m3u8DL-RE -sv res="1080*":codec=hvc1:for=best "https://cdn-videos.domestika.org/videos/000/075/866/403eee36358e32a00ab823db3c1dd83b/master.m3u8?1731344584" --save-dir "domestika_courses///M8- Sewing a Peplum Top" --save-name "6_Hemming Curves Edges"

**Comment by CoralineKoralina** [comment]
> I have this issue even though I installed everything (this code, ffmpeg, N_m3u8DL-RE) for windows.
> 
> Error downloading video: Error: Command failed: N_m3u8DL-RE -sv res="1080*":codec=hvc1:for=best "https://cdn-videos.domestika.org/videos/000/075/866/403eee36358e32a00ab823db3c1dd83b/master.m3u8?1731344584" --save-dir "domestika_courses///M8- Sewing a Peplum Top" --save-name "6_Hemming Curves Edges"

Actually it worked even though it threw these errors, I just had to download the full course a few times because there was always something missing. But now I have a full course downloaded. 
It would be great if there was a check whether a video is already present in the folders to avoid multiple copies and just skip the video. @ReneR97 please consider this for the next update. And thank you!
