### ISSUE TITLE
Issue with "credentials" Cookie and Alternative for .exe File on Linux/macOS

### ISSUE THREAD

**Issue by spyroskotsakis** [ReneR97/domestika-downloader#45]
Hello,

I noticed that the "_credentials_" cookie isn't available. Is this a known issue? Are there plans to update the script to address this? Additionally, is there an alternative to the .exe file for running the script on Linux or macOS?

Thank you in advance

**Comment by CzarParra** [comment]
Did you download the extension on Chrome?

Look, It shows to me the cookie

![image](https://github.com/ReneR97/domestika-downloader/assets/20304467/262b4a5f-0e8e-4b7c-8e75-9ba8fd7e7300)

**Comment by dimak771** [comment]
You can see all value in Safary, in Developer - Show Web Inspector, next - Storage - Cookies

**Comment by MundoMedia** [comment]
The Cookie Editor plugin displays more info on the Firefox version than on the Chrome version.
Use Cookie Editor by cgagnier on Firefox for this.

**Comment by alexbelgium** [comment]
For running on linux, use the appropriate binary for you device. For example : `curl -sL https://github.com/user-or-org/repo/archive/sha1-or-ref.tar.gz | tar xz -C . --strip-components=1`, then just remove the .exe in the name of the binary in the index.js to refer to the binary you've just extracted. This script considers that you execute it from the directory of the index.js

**Comment by kitzstanza** [comment]
> For running on linux, use the appropriate binary for you device from this site https://github.com/nilaoda/N_m3u8DL-RE/releases. For example : `curl -sL https://github.com/nilaoda/N_m3u8DL-RE/releases/download/v0.2.0-beta/N_m3u8DL-RE_Beta_linux-x64_20230628.tar.gz | tar xz -C . --strip-components=1 && sudo ln -s N_m3u8DL-RE /usr/bin/N_m3u8DL-RE.exe`

Downloading the appropriate version for the device if on a Mac will not be an exe file. I tried running the script and it needs the .exe extension.  I tried adding the .exe extension to my x64 version of N_m3u8DL-RE  and it throws this error:

Error: Command failed: N_m3u8DL-RE -sv res="1080*":codec=hvc1:for=best "[cdn video URL]" --save-dir "path/to- -Export- window" --save-name "0_"Export" window"
/bin/sh: N_m3u8DL-RE: command not found

**Comment by alexbelgium** [comment]
Hi, indeed I saw that too but did not correct my message. I'll correct it above. You need go be sure to have execute permissions, keep the filename as such, and rename the binary file in the index.js

**Comment by kitzstanza** [comment]
None of this seemed to work - it's like the version of N_m3u8DL-RE for MacOS is using different method names or something.

**Comment by caaruiz** [comment]
For Linux and maybe MacOS:

Ended up making the binary executable using chmod +x N_m3u8DL-RE and   making following change to make it run.

```
let log = await exec(`./N_m3u8DL-RE -sv res="1080*":codec=hvc1:for=best "${vData.playbackURL}" --save-dir "domestika_courses/${title}/${vData.section}/${unitTitle}" --save-name "${index}_${vData.title.trimEnd()}"`);
let log2 = await exec(`./N_m3u8DL-RE --auto-subtitle-fix --sub-format SRT --select-subtitle lang="${subtitle_lang}":for=all "${vData.playbackURL}" --save-dir "domestika_courses/${title}/${vData.section}/${unitTitle}" --save-name "${index}_${vData.title.trimEnd()}"`);


```

It solved the /bin/sh: N_m3u8DL-RE: command not found error message. I was able to download without any issues.
