### ISSUE TITLE
Problem with the Portuguese language

### ISSUE THREAD

**Issue by Krunsher** [ReneR97/domestika-downloader#5]
Hello, my language is Portuguese, but I am not able to download subtitles in Portuguese. I've already tested in English and Italian and they worked (en, it)
For my language I already tried:
pt, por, po and pt-br and subtitle files are not downloaded in the folder.
Do you know what this code would be to download in Portuguese? Can you test?

**Comment by ReneR97** [comment]
Portuguese should be "pt".
Just tried it with a course i know has Portuguese subtitles and it worked without a problem.
Are you sure your course has Portuguese subtitles? 
Have you tried enabling debug and seeing if it gives you any errors?

**Comment by Krunsher** [comment]
It worked. I don't know what was going on. @ReneR97 


Do you know if it is possible to create a browser extension that filters Domestika courses by language? This is not possible natively in the web version, only in their app.

**Comment by ReneR97** [comment]
Happy that it worked. 

I dont know if thats possible. that might be something thats either really hard or really easy, depending on how much information domestika gives you
