### ISSUE TITLE
Getting "TypeError: Cannot read properties of null (reading '1')"

### ISSUE THREAD

**Issue by pskumaresh06** [ReneR97/domestika-downloader#8]
Hello,

My link:
const course_url = 'https://www.domestika.org/en/courses/4911-sculpture-and-color-polychrome-techniques/course';
const subtitle_lang = 'en';

while performing `npm run start` getting the below error:
![image](https://github.com/ReneR97/domestika-downloader/assets/13378548/65e820a0-e2ea-47e6-8e05-bae3cd7d3636)

Any suggestions. Thanks in advance for your efforts.

**Comment by ReneR97** [comment]
did you fill in the "_credentials_ " variable with the correct value?

**Comment by pskumaresh06** [comment]
Yes. I collected "_credentials_" value from Cookie Editor and placed in the below command location:

const _credentials_ = ''

Thanks

**Comment by ThePantaloon** [comment]
I got this too today; everything was fine last week I downloaded 6 courses with no issues.

**Comment by Kayzzy** [comment]
Try this.

After copying the cookies & credentials to code editor, try running it this way.

Follow this three(3) sequences, see attached screenshot too.

npm i
npm run
npm start


![image](https://github.com/ReneR97/domestika-downloader/assets/20745401/a4fe8dbf-bfa8-4156-b329-a236ebd26088)

**Comment by G419** [comment]
Hello,
I am experiencing the same issue. Following the three steps above, steps 1 and 2 run fine identically to the above. Step 3 throws the error of the initial post. Should the raw cookie value of _credentials_ be modified in some way?
Thank you.

**Comment by ThePantaloon** [comment]
Guys, I found the reason for this error.
The cookie editor sometimes shows the values without encoding, instead of "{" = "%7B" same at the end too "}" = "%7D" and in the middle ":" = "%3A" I changed them manually and it worked, sometimes it shows it correctly that's why we all baffled

**Comment by ReneR97** [comment]
> Guys, I found the reason for this error. The cookie editor sometimes shows the values without encoding, instead of "{" = "%7B" same at the end too "}" = "%7D" and in the middle ":" = "%3A" I changed them manually and it worked, sometimes it shows it correctly that's why we all baffled


Hey, 
thanks for looking into this and finding the problem. Didnt have a lot of time lately for this. 
If this also fixes the problem for the other people here, please let me know

**Comment by G419** [comment]
> Guys, I found the reason for this error. The cookie editor sometimes shows the values without encoding, instead of "{" = "%7B" same at the end too "}" = "%7D" and in the middle ":" = "%3A" I changed them manually and it worked, sometimes it shows it correctly that's why we all baffled

Thank you. This sounded highly promising but sadly didn't resolve it for me (replaced 1x"{", 1x"}" and 3x":") . I have also tried to remplace "-" to "%2D" but to avail.

**Comment by ThePantaloon** [comment]
Make sure it looks something like this:

{%22accessToken%22:%22zvyu-hHMChJ99oojqqw2U2suXMlcCS8ypIZ69f8fK-Q%22%2C%22refreshToken%22:%22KdvRRmv_WbrDf7FUjKHR25nb8kBDCtwcQKw0AF79W7k%22%2C%22isEmpty%22:false}

**Comment by G419** [comment]
> Make sure it looks something like this:
> 
> {%22accessToken%22:%22zvyu-hHMChJ99oojqqw2U2suXMlcCS8ypIZ69f8fK-Q%22%2C%22refreshToken%22:%22KdvRRmv_WbrDf7FUjKHR25nb8kBDCtwcQKw0AF79W7k%22%2C%22isEmpty%22:false}

Yes, this is exactly what the cookie editor gives me: Here's mine:

{%22accessToken%22:%22PrByf1mZLV5Gzg0hdJxEV1LQ9LZj2c3sWt8w614NFZ0%22%2C%22refreshToken%22:%22wmPf8ampoMEzAyLelw3pXu9neDAAEx3XHo1FtBQh-KQ%22%2C%22isEmpty%22:false}

**Comment by benede1** [comment]
hello I am speaking through a translator so I do not know if I understand well, the solution I found was as the partner says is to replace {" = "%7B" , "}" = "%7D". ,":" = "%3A" but the difference is that there are 3 parts where "%3A" is replaced by ":" the first is after the beginning, the second in the middle and the third before the end of the .

I leave an example of how it should be
![ejemplo](https://github.com/ReneR97/domestika-downloader/assets/144130848/6d0d79dd-5bc9-4cf4-9626-e23e38d20ece)


#

**Comment by Minhhl03** [comment]
Hello, replacing characters doesn't work for me! Any other solutions?

**Comment by kanishkamad** [comment]
![Screenshot (173)](https://github.com/ReneR97/domestika-downloader/assets/106143773/a7551afa-6366-43e9-b022-d731a6377c6d)

I'm getting only these from the cookie editor. Where I can fine the credential value ?

**Comment by kanishkamad** [comment]
> @kanishkamad Just scroll down a bit, should be more cookies

Thank you @ReneR97 . It was an issue with my browser. I just change the browser and it's fixed.
