### ISSUE TITLE
fetch not defined

### ISSUE THREAD

**Issue by ThePantaloon** [ReneR97/domestika-downloader#9]
Hi, I'm getting this err

<img width="640" alt="Screenshot 2023-07-04 091354" src="https://github.com/ReneR97/domestika-downloader/assets/24735155/ec1d8aa6-797c-46ed-9fb7-1378237a6fdd">

**Comment by ReneR97** [comment]
Hey,
be sure you are using a node version 18+.
To check you can type "node -v" into the console. 
if its below version 18, just update it and it should work

**Comment by ThePantaloon** [comment]
Worked! Thank you very much
